import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/themeProviders";
import localFont from "next/font/local";


// 기본 글꼴
const inter = Inter({ subsets: ["latin"] });

// 프리텐다드 글꼴
const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display : "swap", 
  weight: "45 920", // weight 를 입력하지 않으면, WebKit 기반의 브라우저에서 굵기가 잘못 렌더링 될 수 있으니 주의
})


export const metadata: Metadata = {
  title: "DJ Portfolio",
  description: "Generated by DJ NEXT.js 14 ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className} >
        <ThemeProvider
          attribute="class"
          // defaultTheme="dark" // dark 모드
          defaultTheme="system"  // light 모드
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
